### ISSUE TITLE
Upstream Checklist

### ISSUE THREAD

**Issue by cfriedt** [zephyrproject-rtos/gsoc-2022-thrift#147]
### Overview

This is an umbrella issue meant to illustrate any steps required to
* Upstream this project (`gsoc-2022-thrift`) as an external module to e.g. `https://github.com/zephyrproject-rtos/thrift`
  - add an entry to `west.yml` in [zephyr](https://github.com/zephyrproject-rtos/zephyr)
  - move tests directly into Zephyr repository (e.g. `tests/lib/thrift`)
  - move samples directly into Zephyr repository (e.g. `samples/lib/thrift`)
* Upstream changes to [Thrift](https://github.com/apache/thrift)
  - likely will be a part of the upcoming 0.18.0 release
* Improve Zephyr support for 3rd-party libraries like Thrift

### Upstream `gsoc-2022-thrift` to `zephyr`

These are mainly housekeeping, code-quality, and CI integration efforts.

- [x] #131
- [x] #139
- [x] #144
- [x] #161 
- [x] #160
- [x] #158

### Upstream changes to Thrift

Here, we want to mitigate any small changes made to Thrift to get it to build against Zephyr. Changes here should be upstreamed directory to the Apache Thrift project on GitHub. If a change is not suitable to upstream to Thrift, there should be good justification (e.g. insufficient support for C++11, and a workaround for Zephyr is needed)

- [x] apache/thrift#2680
- [x] apache/thrift#2681
- [x] apache/thrift#2682
- [x] apache/thrift#2687
- [x] apache/thrift#2630
- [x] apache/thrift#2720
- [x] apache/thrift#2689
- [x] apache/thrift#2722
- [x] apache/thrift#2723

🥳 

### Zephyr Improvements

Fix Zephyr-Newlib POSIX incompatibilties:
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/51781
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/52003
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/52087
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/52173
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/52313  
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/52316

Clean Up POSIX headers
- [x] https://github.com/zephyrproject-rtos/zephyr/pull/51771

### SDK / C++ / CI:
- [x] zephyrproject-rtos/gsoc-2022-thrift#149 (remove in-tree workaround)
- [x] https://github.com/zephyrproject-rtos/docker-image/pull/133
- [ ] zephyrproject-rtos/zephyr#45785 (can be deferred)

cc @stephanosio
